import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createDatabase,validateDatabase,publicCatalog,filterProducts } from '../assets/js/catalog-model.js';
function product(id='sofa'){return {id,name:'Blue Sofa',sku:id.toUpperCase(),description:'Fabric sofa',priceCents:79900,oldPriceCents:99900,stock:2,category:'living-room',subcategory:'sofas',dimensions:'80 × 36 × 34 in',material:'Fabric',finish:'Blue',images:['assets/products/sofa.webp'],active:true,available:true,featured:true};}
function database(){const d=createDatabase();d.subcategories.push({id:'sofas',category:'living-room',name:'Sofas',description:'',active:true});d.products.push(product());return d;}
test('new database creates categories and no fabricated inventory/orders',()=>{const d=createDatabase();assert.equal(d.categories.length,6);assert.equal(d.products.length,0);assert.equal(d.orders.length,0);assert.deepEqual(validateDatabase(d),d);});
test('category/subcategory identity and unique SKUs are enforced before saving',()=>{for(const patch of [{category:'missing'},{subcategory:'wrong'},{priceCents:-1},{oldPriceCents:NaN},{images:['javascript:alert(1)']},{images:['assets/products/../secret.jpg']}]){const d=database();Object.assign(d.products[0],patch);assert.throws(()=>validateDatabase(d));}const d=database();d.products.push({...product('other'),sku:'sofa'});assert.throws(()=>validateDatabase(d));d.products.pop();d.subcategories[0].category='bedroom';assert.throws(()=>validateDatabase(d));});
test('public export omits private orders and imported private fields and hidden catalog records',()=>{const d=database();d.orders.push({id:'o1',number:'PRIVATE-1',name:'Private Person',email:'private@tests.invalid',phone:'5551234',notes:'Private notes',createdAt:new Date().toISOString(),items:[{productId:'sofa',name:'Blue Sofa',sku:'SOFA',priceCents:79900,quantity:1}]});d.products[0].privateNotes='Never publish';d.settings.privatePassword='secret';const published=publicCatalog(d),json=JSON.stringify(published);assert.equal(Object.hasOwn(published,'orders'),false);for(const value of ['Private Person','private@tests.invalid','Private notes','Never publish','secret'])assert.equal(json.includes(value),false);d.subcategories[0].active=false;assert.equal(publicCatalog(d).products.length,0);});
test('database roundtrip preserves price history, product specifications and private local order snapshots',()=>{const d=database();d.orders.push({id:'o1',number:'EMAIL-1',name:'Customer',email:'',phone:'',notes:'',createdAt:new Date().toISOString(),items:[{productId:'sofa',name:'Blue Sofa',sku:'SOFA',priceCents:79900,quantity:2}]});d.products[0].priceCents=69900;const copy=validateDatabase(JSON.parse(JSON.stringify(d)));assert.equal(copy.products[0].oldPriceCents,99900);assert.equal(copy.products[0].material,'Fabric');assert.equal(copy.orders[0].items[0].priceCents,79900);copy.orders.push({...copy.orders[0],id:'o2',number:'email-1'});assert.throws(()=>validateDatabase(copy));});
test('2,000 products can be searched and sorted without modifying the database',()=>{const d=database();d.products=Array.from({length:2000},(_,i)=>({...product('p'+i),name:'Sofa '+i,priceCents:10000+i,featured:i<4}));assert.equal(validateDatabase(d).products.length,2000);assert.equal(filterProducts(d,{category:'living-room',subcategory:'sofas'}).length,2000);const found=filterProducts(d,{search:'p1999'});assert.equal(found.length,1);assert.equal(found[0].id,'p1999');assert.equal(filterProducts(d,{sort:'price-desc'})[0].id,'p1999');assert.equal(d.products[0].id,'p0');});
