"""Actual SDK, Auth and Firestore integration: no adapters or production writes."""
from playwright.sync_api import sync_playwright,expect
EDITOR='http://127.0.0.1:4175/furniture-editor.html?emulator=1'
BASE='http://127.0.0.1:4173/'
def login(page):
 page.locator('#firebase-login [name="password"]').fill('Emulator-only-test-1020');page.locator('#firebase-login .button-secondary').click();expect(page.locator('#firebase-status')).to_contain_text('Connected to Firebase',timeout=15000)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox']);ctx=b.new_context();page=ctx.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('dialog',lambda d:d.accept());page.goto(EDITOR);expect(page.locator('#save-status')).to_contain_text('Saved on this computer')
 page.locator('#new-product').click();page.locator('#product-form [name="name"]').fill('Cloud Oak Sofa');page.locator('#product-form [name="sku"]').fill('CLOUD1');page.locator('#product-form [name="price"]').fill('799');page.locator('#product-form [name="oldPrice"]').fill('999');page.locator('#product-form [name="dimensions"]').fill('80 × 36 × 34 in');page.locator('#product-form [name="material"]').fill('Oak');page.locator('#product-photo-upload').set_input_files('assets/images/sofa.webp');expect(page.locator('#product-image-paths')).not_to_have_value('');page.locator('#product-form .button-primary').click();expect(page.locator('#product-editor')).to_be_hidden()
 page.locator('[data-tab="orders"]').click();page.locator('#new-order').click();page.locator('#order-form [name="number"]').fill('PRIVATE-CLOUD-001');page.locator('#order-form [name="notes"]').fill('PRIVATE CLOUD CUSTOMER');page.locator('#order-add-product').select_option(label='Cloud Oak Sofa');page.locator('#add-order-line').click();page.locator('#order-form .button-primary').click();expect(page.locator('#order-editor')).to_be_hidden()
 login(page);page.locator('#firebase-publish').click();expect(page.locator('#firebase-status')).to_contain_text('Published to Firebase: 1 public products and 1 private orders.',timeout=30000)
 fresh=b.new_context();other=fresh.new_page();other.on('dialog',lambda d:d.accept());other.goto(EDITOR);expect(other.locator('#save-status')).to_contain_text('0 products');login(other);other.locator('[data-tab="orders"]').click();expect(other.locator('#order-results')).to_contain_text('PRIVATE CLOUD CUSTOMER',timeout=15000);expect(other.locator('#save-status')).to_contain_text('0 products');other.locator('#firebase-load').click();expect(other.locator('#firebase-status')).to_contain_text('Loaded from Firebase: 1 products and 1 private orders.',timeout=15000);expect(other.locator('#editor-products')).to_contain_text('Cloud Oak Sofa');expect(other.locator('#editor-products del')).to_have_text('$999');expect(other.locator('#editor-products img')).to_have_js_property('complete',True);assert other.locator('#editor-products img').evaluate('(img)=>img.naturalWidth>0');other.locator('[data-tab="orders"]').click();expect(other.locator('#order-results')).to_contain_text('PRIVATE CLOUD CUSTOMER');other.reload();expect(other.locator('#save-status')).to_contain_text('1 products');expect(other.locator('#save-status')).to_contain_text('1 local orders');login(other);other.locator('[data-tab="orders"]').click()
 customer=b.new_context();store=customer.new_page();requests=[];store.on('request',lambda r:requests.append(r.url));store.goto(BASE+'store.html?emulator=1');expect(store.locator('.product-card')).to_have_count(1,timeout=15000);expect(store.locator('.product-card')).to_contain_text('Cloud Oak Sofa');expect(store.locator('.product-card del')).to_have_text('$999');assert store.locator('.product-card img').evaluate('(img)=>img.complete&&img.naturalWidth>0');assert not any('catalog.json' in u for u in requests);assert 'PRIVATE CLOUD CUSTOMER' not in store.content();store.locator('[data-action="add"]').click();expect(store.locator('[data-cart-count]').first).to_have_text('1');store.goto(BASE+'order.html?emulator=1');expect(store.locator('.cart-item')).to_have_count(1,timeout=15000);expect(store.locator('#cart-total')).to_have_text('$799');store.locator('#submit-inquiry').click();expect(store.locator('#inquiry-confirmation')).to_be_visible(timeout=15000);number=store.locator('#created-order-number').inner_text();expect(store.locator('#inquiry-products img')).to_be_visible();expect(other.locator('#order-results')).to_contain_text(number,timeout=15000);expect(other.locator('#order-results img').last).to_be_visible();assert other.locator('#order-results img').last.evaluate('(img)=>img.complete&&img.naturalWidth>0')
 dormant=b.new_context();old=dormant.new_page();old.on('dialog',lambda d:d.accept());old.goto(EDITOR);login(old);old.locator('#firebase-load').click();expect(old.locator('#firebase-status')).to_contain_text('2 private orders');old.locator('#firebase-logout').click()
 # Cache the website order on both computers before deletion, proving copies do not reappear.
 other.locator('#firebase-load').click();expect(other.locator('#firebase-status')).to_contain_text('2 private orders');page.locator('#firebase-load').click();expect(page.locator('#firebase-status')).to_contain_text('2 private orders');page.locator('[data-tab="orders"]').click()
 row=other.locator('.editor-order').filter(has=other.locator('h3',has_text=number));row.locator('[data-delete-order]').click();expect(other.locator('#editor-feedback')).to_contain_text('permanently deleted',timeout=15000);expect(other.locator('#order-results')).not_to_contain_text(number);expect(page.locator('#order-results')).not_to_contain_text(number,timeout=15000);expect(page.locator('#save-status')).to_contain_text('1 local orders');other.reload();expect(other.locator('#save-status')).to_contain_text('1 local orders');login(other);other.locator('[data-tab="orders"]').click();expect(other.locator('#order-results')).not_to_contain_text(number)
 login(old);expect(old.locator('#save-status')).to_contain_text('1 local orders',timeout=15000);old.reload();expect(old.locator('#save-status')).to_contain_text('1 local orders');dormant.close()
 # Direct lookup now confirms the customer inquiry really is gone.
 store.reload();store.locator('#public-order-number').fill(number);store.locator('#public-order-lookup button').click();expect(store.locator('#lookup-feedback')).to_contain_text('No order',timeout=15000)

 other.locator('[data-tab="catalog"]').click();login(other);other.locator('#firebase-publish').click();expect(other.locator('#editor-feedback')).to_contain_text('Load from Firebase before publishing');other.locator('#firebase-load').click();expect(other.locator('#firebase-status')).to_contain_text('Loaded from Firebase');other.locator('[data-edit-product]').click();other.locator('#product-form [name="price"]').fill('699');other.locator('#product-form .button-primary').click();other.locator('#firebase-publish').click();expect(other.locator('#firebase-status')).to_contain_text('Published to Firebase',timeout=30000);store.goto(BASE+'store.html?emulator=1');expect(store.locator('.product-card del')).to_have_text('$799',timeout=15000);expect(store.locator('.product-card .current-price')).to_have_text('$699')
 page.locator('#firebase-publish').click();expect(page.locator('#editor-feedback')).to_contain_text('online catalog changed',timeout=15000)
 # A published private record is deleted too, and a fresh cloud restore cannot recover it.
 other.locator('[data-tab="orders"]').click();other.locator('[data-delete-order]').click();expect(other.locator('#editor-feedback')).to_contain_text('permanently deleted',timeout=15000);expect(page.locator('#save-status')).to_contain_text('0 local orders',timeout=15000);other.locator('#firebase-load').click();expect(other.locator('#firebase-status')).to_contain_text('0 private orders',timeout=15000)
 assert not errors,errors;b.close()
print('PASS: real verified-email login; product/photos/private-order Firebase publication; restoration in a fresh editor; public catalog/cart/prices without local JSON; stale publication denied; permanent public/private deletion; connected and previously disconnected copies removed.')
