import { test,before,after } from 'node:test';
import { readFile } from 'node:fs/promises';
import { initializeTestEnvironment,assertFails,assertSucceeds } from '@firebase/rules-unit-testing';
import { doc,getDoc,getDocs,collection,setDoc,updateDoc,deleteDoc,serverTimestamp,Timestamp } from 'firebase/firestore';
let env;const number=n=>`FD-20261010-${String(n).padStart(32,'A')}`,line=()=>['sofa','Blue Sofa','S1','79900'].join('\t'),request=n=>({number:n,items:{'0':line()},createdAt:serverTimestamp()});
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-furniture-discounters',firestore:{host:'127.0.0.1',port:8080,rules:await readFile('firestore.rules','utf8')}});await env.clearFirestore();});after(()=>env?.cleanup());
test('unauthenticated customers can create and look up a request by its full number',async()=>{const db=env.unauthenticatedContext().firestore(),n=number('1');await assertSucceeds(setDoc(doc(db,'pickupRequests',n),request(n)));await assertSucceeds(getDoc(doc(db,'pickupRequests',n)));await assertSucceeds(getDoc(doc(db,'pickupRequests',number('2'))));});
test('enumeration, modifying and deleting public requests are denied',async()=>{const db=env.unauthenticatedContext().firestore(),n=number('3');await assertSucceeds(setDoc(doc(db,'pickupRequests',n),request(n)));await assertFails(getDocs(collection(db,'pickupRequests')));await assertFails(updateDoc(doc(db,'pickupRequests',n),{items:{}}));await assertFails(deleteDoc(doc(db,'pickupRequests',n)));await assertFails(getDoc(doc(db,'pickupRequests/SHORT-NUMBER')));});
test('contact details, status fields, forged timestamps and invalid line values cannot be stored',async()=>{const db=env.unauthenticatedContext().firestore();let count=20;for(const change of [{email:'private@tests.invalid'},{customer:{name:'Private'}},{status:'ready'},{createdAt:Timestamp.fromMillis(0)},{items:{}},{items:Object.fromEntries(Array.from({length:21},(_,i)=>[String(i),line()]))},{items:{'0':['sofa','Blue Sofa','S1','-1'].join('\t')}},{items:{'0':['sofa','Blue Sofa','S1','79900',2].join('\t')}},{items:{'0':['sofa','Blue Sofa','S1','79900','secret'].join('\t')}},{items:{'0':['sofa','x'.repeat(161),'S1','79900'].join('\t')}}]){const n=number((count++).toString(16).toUpperCase());await assertFails(setDoc(doc(db,'pickupRequests',n),{...request(n),...change}));}});
test('all 20 bounded lines are validated, including the last line',async()=>{const db=env.unauthenticatedContext().firestore(),n=number('50');await assertSucceeds(setDoc(doc(db,'pickupRequests',n),{...request(n),items:Object.fromEntries(Array.from({length:20},(_,i)=>[String(i),['p'+i,'Blue Sofa','S1','79900'].join('\t')]))}));const bad=Object.fromEntries(Array.from({length:20},(_,i)=>[String(i),['p'+i,'Blue Sofa','S1','79900'].join('\t')]));bad[19]='p19\tBlue Sofa\tS1\t-1';const other=number('51');await assertFails(setDoc(doc(db,'pickupRequests',other),{...request(other),items:bad}));});
test('catalog writes, staff escalation and private order collections stay inaccessible',async()=>{for(const ctx of [env.unauthenticatedContext(),env.authenticatedContext('legacy',{admin:true})]){const db=ctx.firestore();for(const path of ['products/p','categories/c','staff/legacy','orders/private','pickupRequests/'+number('1')+'/private/details']){await assertFails(setDoc(doc(db,path),{role:'admin'}));await assertFails(getDoc(doc(db,path)));}}});
test('only verified store email or the designated UID may publish; snapshots and private orders are separated',async()=>{
 const owner=env.authenticatedContext('new-store-owner',{email:'furniture.discounters.offcial@gmail.com',email_verified:true}).firestore(),publicDb=env.unauthenticatedContext().firestore(),unverified=env.authenticatedContext('unverified',{email:'furniture.discounters.offcial@gmail.com',email_verified:false,admin:true}).firestore();
 const pointer={revision:'version1',parts:1,updatedAt:serverTimestamp()};
 await assertFails(setDoc(doc(unverified,'catalog/current'),pointer));await assertFails(setDoc(doc(publicDb,'catalog/current'),pointer));
 await assertSucceeds(setDoc(doc(owner,'catalogVersions/version1/parts/0'),{json:'{"products":[]}'}));
 await assertFails(getDoc(doc(publicDb,'catalogVersions/version1/parts/0')));
 await assertSucceeds(setDoc(doc(owner,'catalog/current'),pointer));await assertSucceeds(getDoc(doc(publicDb,'catalogVersions/version1/parts/0')));await assertFails(getDocs(collection(publicDb,'catalogVersions/version1/parts')));
 await assertSucceeds(setDoc(doc(owner,'editor/current'),pointer));await assertSucceeds(setDoc(doc(owner,'editorVersions/version1/parts/0'),{json:'private catalog'}));await assertFails(getDoc(doc(publicDb,'editor/current')));await assertFails(getDoc(doc(publicDb,'editorVersions/version1/parts/0')));
 await assertSucceeds(setDoc(doc(owner,'orders/private1'),{json:'{"name":"Private Customer"}',revision:'version1',updatedAt:serverTimestamp()}));await assertSucceeds(getDocs(collection(owner,'orders')));await assertFails(getDocs(collection(publicDb,'orders')));await assertFails(getDoc(doc(publicDb,'orders/private1')));
 await assertFails(updateDoc(doc(owner,'orders/private1'),{extra:'pollution'}));await assertFails(setDoc(doc(owner,'orders/private2'),{json:'x'.repeat(100001),revision:'version1',updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(owner,'catalog/current'),{parts:101}));await assertFails(updateDoc(doc(owner,'catalog/current'),{extra:true}));await assertFails(updateDoc(doc(owner,'catalog/current'),{updatedAt:Timestamp.fromMillis(0)}));
 await assertFails(setDoc(doc(owner,'catalogVersions/version1/parts/1'),{json:'x'.repeat(150001)}));await assertFails(updateDoc(doc(owner,'catalogVersions/version1/parts/0'),{json:'edited'}));
 const photoId='b'.repeat(64);await assertSucceeds(setDoc(doc(owner,'catalogPhotos',photoId),{data:'data:image/webp;base64,AAAA'}));await assertSucceeds(getDoc(doc(publicDb,'catalogPhotos',photoId)));await assertFails(getDocs(collection(publicDb,'catalogPhotos')));await assertFails(updateDoc(doc(owner,'catalogPhotos',photoId),{data:'data:image/svg+xml;base64,AAAA'}));await assertFails(setDoc(doc(owner,'catalogPhotos','c'.repeat(64)),{data:'data:image/svg+xml;base64,AAAA'}));
});

test('only store owners may permanently delete inquiries and private copies',async()=>{const owner=env.authenticatedContext('deleting-owner',{email:'furniture.discounters.offcial@gmail.com',email_verified:true}).firestore(),customer=env.unauthenticatedContext().firestore(),n=number('99');await assertSucceeds(setDoc(doc(customer,'pickupRequests',n),request(n)));for(const db of [customer,env.authenticatedContext('unverified-delete',{email:'furniture.discounters.offcial@gmail.com',email_verified:false}).firestore(),env.authenticatedContext('other-delete',{email:'other@tests.invalid',email_verified:true,admin:true}).firestore()])await assertFails(deleteDoc(doc(db,'pickupRequests',n)));await assertFails(updateDoc(doc(owner,'pickupRequests',n),{items:{}}));await assertSucceeds(deleteDoc(doc(owner,'pickupRequests',n)));await assertSucceeds(setDoc(doc(owner,'orders/delete-copy'),{json:'{}',revision:'v1',updatedAt:serverTimestamp()}));await assertFails(deleteDoc(doc(customer,'orders/delete-copy')));await assertSucceeds(deleteDoc(doc(owner,'orders/delete-copy')));});
